// <auto-generated />
using System;
using DOTNET_Core_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DOTNET_Core_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DOTNET_Core_Project.Models.Hastaneler", b =>
                {
                    b.Property<int>("HastaneNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CalisanSayisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaneAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaneTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SorumluKisi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HastaneNo");

                    b.ToTable("hastanelers");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Musteriler", b =>
                {
                    b.Property<int>("MusteriNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MusteriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PetNo")
                        .HasColumnType("int");

                    b.HasKey("MusteriNo");

                    b.HasIndex("PetNo");

                    b.ToTable("musterilers");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Pets", b =>
                {
                    b.Property<int>("PetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PetAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetHastalik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetYas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurNo")
                        .HasColumnType("int");

                    b.HasKey("PetNo");

                    b.HasIndex("TurNo");

                    b.ToTable("petss");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Randevular", b =>
                {
                    b.Property<int>("RandevuNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MusteriNo")
                        .HasColumnType("int");

                    b.Property<string>("RandevuSaati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("VeterinerNo")
                        .HasColumnType("int");

                    b.HasKey("RandevuNo");

                    b.HasIndex("MusteriNo");

                    b.HasIndex("VeterinerNo");

                    b.ToTable("randevulars");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Turler", b =>
                {
                    b.Property<int>("TurNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TurAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TurSayisi")
                        .HasColumnType("int");

                    b.HasKey("TurNo");

                    b.ToTable("turlers");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Veterinerler", b =>
                {
                    b.Property<int>("VeterinerNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HastaneNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Maas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VeterinerAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeterinerTelefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VeterinerNo");

                    b.HasIndex("HastaneNo");

                    b.ToTable("veterinerlers");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Musteriler", b =>
                {
                    b.HasOne("DOTNET_Core_Project.Models.Pets", "pets")
                        .WithMany()
                        .HasForeignKey("PetNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pets");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Pets", b =>
                {
                    b.HasOne("DOTNET_Core_Project.Models.Turler", "turler")
                        .WithMany()
                        .HasForeignKey("TurNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("turler");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Randevular", b =>
                {
                    b.HasOne("DOTNET_Core_Project.Models.Musteriler", "musteriler")
                        .WithMany()
                        .HasForeignKey("MusteriNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DOTNET_Core_Project.Models.Veterinerler", "veterinerler")
                        .WithMany()
                        .HasForeignKey("VeterinerNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("musteriler");

                    b.Navigation("veterinerler");
                });

            modelBuilder.Entity("DOTNET_Core_Project.Models.Veterinerler", b =>
                {
                    b.HasOne("DOTNET_Core_Project.Models.Hastaneler", "hastaneler")
                        .WithMany()
                        .HasForeignKey("HastaneNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hastaneler");
                });
#pragma warning restore 612, 618
        }
    }
}
